services:
  - type: web
    name: nidana-ai-backend
    env: docker
    region: oregon 
    plan: free
    dockerContext: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
    autoDeploy: true

